Filetype: Flipper TOTP plugin config file
Version: 14
CryptoVersion: 3
CryptoKeySlot: 11
# Config file format specification can be found here: https://t.ly/zwQjE
Timezone: 0.000000
NotificationMethod: 3
AutomationMethod: 1
AutomationKbLayout: 0
BadBTProfile: 0
AutomationInitialDelay: 500
Font: 0
UITokenDigitGrouping: 0
Salt: 19 7C 74 30 2D 25 C1 A0 DD 1B AC 03 80 46 20 23
Crypto: E0 72 A1 F1 23 5C 00 00 00 00 00 00 00 00 00 00
PinIsSet: false
