[
  {
    "wifi": [
      {
        "ssid": "myNetSSID",
        "pwd": "oVrMpIQYWl7VcadqFC4QWQ==",
        "secure": true
      },
      {
        "ssid": "S26 Ultra de Luca",
        "pwd": "hi4R0sl0WaQ+qbB3btBHtg==",
        "secure": true
      }
    ],
    "favorite": [
      {
        "name": "Bruce (T-Embed) - pr3y (t-embed-cc1101)",
        "fid": "CFW1267810b943759f709924d24ed3a2",
        "link": ""
      },
      {
        "name": "FlipperZero (need SD files) - Sor3nt (t-embed-cc1101)",
        "fid": "CFWbb7c3a3f21a6674e575b1e75ef9e2",
        "link": ""
      },
      {
        "name": "Capibara Zero - Capibara (t-embed-cc1101)",
        "fid": "CFW95253bac7d0c179e5867e7790190c",
        "link": ""
      }
    ],
    "onlyBins": false,
    "bootToApp": false,
    "noDotFiles": false,
    "autoBackup": true,
    "askSpiffs": true,
    "bright": 100,
    "dimmerSet": 20,
    "e0:72:a1:f1:23:5c-Lilygo T-Embed CC1101": 3,
    "FGCOLOR": 2016,
    "BGCOLOR": 0,
    "ALCOLOR": 63488,
    "odd": 12485,
    "even": 13029,
    "dev": false,
    "autoConnect": true,
    "wui_usr": "admin",
    "wui_pwd": "launcher",
    "dwn_path": "/downloads/"
  }
]